name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital

variables:
  - template: project.yml

jobs:
  - job: teardown
    displayName: PR Teardown
    timeoutInMinutes: 30
    pool:
      name: 'AWS-ECS'
      vmImage: 'ubuntu-latest'
    steps:
      - checkout: self

      - bash: |
          env | sort
        displayName: Display environment variables

      - bash: |
          name=$(FULLY_QUALIFIED_SERVICE_NAME)
          WORKSPACE=$(echo $name | grep -oE 'pr-[0-9]+$')
          echo $WORKSPACE
          echo "##vso[task.setvariable variable=WORKSPACE]$WORKSPACE"
        displayName: Set workspace tag

      - template: "azure/components/aws-assume-role.yml@common"
        parameters:
            role: "auto-ops"
            profile: "apim-dev"
            aws_account: "dev"

      - bash: |
          echo "##vso[task.setvariable variable=AWS_DEFAULT_REGION]eu-west-2"
        displayName: Set AWS default region

      - bash: |
          export AWS_PROFILE=apim-dev
          account_id="$(aws sts get-caller-identity --query Account --output text)"

          cd terraform
          make init
          terraform workspace select $(WORKSPACE) && make init && terraform destroy -force && /
          terraform workspace select default && terraform workspace delete $(WORKSPACE)
        displayName: Destroy terraform PR workspace and linked resources

      - template: ./templates/remove_kvm_entry.yml
        parameters:
          workspace_tag: $(WORKSPACE)
